default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  identity_app:
    <<: *default
    username: user
    password: password
    database: identity_development
    port: 5434

test:
  identity_app:
    <<: *default
    username: user
    password: password
    database: identity_test
    port: 5435

# production:
#   <<: *default
#   username: <%= ENV["DATABASE_USER"] %>
#   password: <%= ENV["DATABASE_PASSWORD"] %>
#   database: <%= ENV["DATABASE_NAME"] %>
