
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  withdraw_app:
    <<: *default
    host: <%= ENV.fetch("WITHDRAW_DB_HOST") { 'localhost' } %>
    port: <%= ENV.fetch("WITHDRAW_DB_PORT") { 5432 } %>
    username: user
    password: password
    database: withdraw_development

test:
  withdraw_app:
    <<: *default
    host: <%= ENV.fetch("WITHDRAW_DB_HOST") { 'localhost' } %>
    port: <%= ENV.fetch("WITHDRAW_DB_PORT") { 5432 } %>
    username: user
    password: password
    database: withdraw_test
