
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: user
  password: password
  database: withdraw_development
  port: 5436

test:
  <<: *default
  username: user
  password: password
  database: withdraw_test
  port: 5437

# production:
#   <<: *default
#   username: <%= ENV["DATABASE_USER"] %>
#   password: <%= ENV["DATABASE_PASSWORD"] %>
#   database: <%= ENV["DATABASE_NAME"] %>
